export const REFRESH_CATEGORIES = 'REFRESH_CATEGORIES'

export const SAVE_POST = 'SAVE_POST'
export const DELETE_POST = 'DELETE_POST'
export const DETAIL_POST = 'DETAIL_POST'
export const GET_POST = 'GET_POST'
export const EDIT_POST = 'EDIT_POST'
export const VOTE_POST = 'VOTE_POST'
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const SORT_POSTS = 'SORT_POSTS'
export const REFRESH_POSTS = 'REFRESH_POSTS'
export const REFRESH_POSTS_BY_CATEGORY = 'REFRESH_POSTS_BY_CATEGORY'


export const SAVE_COMMENT = 'SAVE_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const GET_COMMENT = 'GET_COMMENT'
export const CLEAR_COMMENT = 'CLEAR_COMMENT'
export const LIST_COMMENTS = 'LIST_COMMENTS'
export const EDIT_COMMENT = 'EDIT_COMMENT'
export const VOTE_COMMENT = 'VOTE_COMMENT'
export const REFRESH_COMMENTS = 'REFRESH_COMMENTS'

export const ERROR_PAGE = 'ERROR_PAGE'